### ISSUE TITLE
Multiple syncup-events with status "done"

### ISSUE THREAD

**Issue by rnng** [forcedotcom/SalesforceMobileSDK-Shared#328] opened 2016-02-04 09:43 UTC
In my Project I experience a problem with smartsync and their sync-events. For one syncup-operation I get two syncup-events. This would be nothing out of the ordinary but they both have the status done (see my screenshot for this). In my screenshot you see also a log with the text "syncup", it is executed immediately before I call the syncup function so this isnt executed twice.

This is very problematic for me because the syncdone-status triggers a new syncdown-event and I dont want this to be done twice.

![image](https://cloud.githubusercontent.com/assets/1899069/12811328/0d095722-cb2c-11e5-9485-03ecfaf0629a.png)

**Comment by wmathurin** [comment] 2016-02-04 16:48
Thanks for reporting this. What version of the SDK are you using? Do you see it on iOS, Android or both?

**Comment by rnng** [comment] 2016-02-05 12:29
Hey,

I am using the newest version from forceios to compile my App.

**Comment by wmathurin** [comment] 2016-02-06 00:55
I can't tell when we will have a fix.
In the mean time, I recommend you keep some state of the javascript side like a map of sync id to sync status. Upon receiving a sync event, update that map. Only proceed if the status received was not already known. That way you will ignore duplicate 'done' events.

**Comment by wmathurin** [comment] 2016-06-24 20:04
We are unable to reproduce the issue in unstable (our soon to be released 4.2).
We tried both SmartSyncExplorer (native) and SmartSyncExplorerHybrid applications.
Closing for now. After 4.2 ships, please retry and let us know if you are still seeing the issue.

**Closed by wmathurin** 2016-06-24 20:04 UTC
Labels: bug
